Repository meshery/meshery-nginx-sm, pull requests merged in 2022-01, with the labels that each got.

#77 Added e2e tests
  .github/install/deploy.yaml
  .github/workflows/e2etests.yaml
  nginx/install.go
Labels: area/ci, area/tests

#82 Added missing "title" fields in schema
  .github/workflows/update-oam-defs.yml
  templates/oam/workloads/v1.2.0/circuitbreaker.nginx-sm.meshery.layer5io.schema.json
  templates/oam/workloads/v1.2.0/httproutegroup.nginx-sm.meshery.layer5io.schema.json
  templates/oam/workloads/v1.2.0/ratelimit.nginx-sm.meshery.layer5io.schema.json
  templates/oam/workloads/v1.2.0/tcproute.nginx-sm.meshery.layer5io.schema.json
  templates/oam/workloads/v1.2.0/trafficsplit.nginx-sm.meshery.layer5io.schema.json
  templates/oam/workloads/v1.2.0/traffictarget.nginx-sm.meshery.layer5io.schema.json
  templates/oam/workloads/v1.2.1/circuitbreaker.nginx-sm.meshery.layer5io.schema.json
  templates/oam/workloads/v1.2.1/httproutegroup.nginx-sm.meshery.layer5io.schema.json
  templates/oam/workloads/v1.2.1/ratelimit.nginx-sm.meshery.layer5io.schema.json
  templates/oam/workloads/v1.2.1/tcproute.nginx-sm.meshery.layer5io.schema.json
  templates/oam/workloads/v1.2.1/trafficsplit.nginx-sm.meshery.layer5io.schema.json
  templates/oam/workloads/v1.2.1/traffictarget.nginx-sm.meshery.layer5io.schema.json
  templates/oam/workloads/v1.3.1/circuitbreaker.nginx-sm.meshery.layer5io.schema.json
  templates/oam/workloads/v1.3.1/httproutegroup.nginx-sm.meshery.layer5io.schema.json
  templates/oam/workloads/v1.3.1/ratelimit.nginx-sm.meshery.layer5io.schema.json
  templates/oam/workloads/v1.3.1/spiffeid.nginx-sm.meshery.layer5io.schema.json
  templates/oam/workloads/v1.3.1/tcproute.nginx-sm.meshery.layer5io.schema.json
  templates/oam/workloads/v1.3.1/trafficsplit.nginx-sm.meshery.layer5io.schema.json
  templates/oam/workloads/v1.3.1/traffictarget.nginx-sm.meshery.layer5io.schema.json
Labels: component/patterns

#87 should fix version problem
  main.go
Labels: area/ci, area/lifecycle, language/go, service-mesh/nginx-sm

#83 Discourse shield is added.
  README.md
Labels: kind/chore
